//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildIndicator.AlertDialler.WebDialer {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:WebdialerSoap", ConfigurationName="WebDialer.WebdialerSoapService")]
    public interface WebdialerSoapService {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:makeCallSoap", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WDDeviceInfo))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        BuildIndicator.AlertDialler.WebDialer.CallResponse makeCallSoap(BuildIndicator.AlertDialler.WebDialer.Credential cred, string dest, BuildIndicator.AlertDialler.WebDialer.UserProfile prof);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:makeCallSoap", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<BuildIndicator.AlertDialler.WebDialer.CallResponse> makeCallSoapAsync(BuildIndicator.AlertDialler.WebDialer.Credential cred, string dest, BuildIndicator.AlertDialler.WebDialer.UserProfile prof);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:endCallSoap", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WDDeviceInfo))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        BuildIndicator.AlertDialler.WebDialer.CallResponse endCallSoap(BuildIndicator.AlertDialler.WebDialer.Credential cred, BuildIndicator.AlertDialler.WebDialer.UserProfile prof);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:endCallSoap", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<BuildIndicator.AlertDialler.WebDialer.CallResponse> endCallSoapAsync(BuildIndicator.AlertDialler.WebDialer.Credential cred, BuildIndicator.AlertDialler.WebDialer.UserProfile prof);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:getProfileSoap", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WDDeviceInfo))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        BuildIndicator.AlertDialler.WebDialer.GetConfigResponse getProfileSoap(BuildIndicator.AlertDialler.WebDialer.Credential cred, string userid);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:getProfileSoap", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<BuildIndicator.AlertDialler.WebDialer.GetConfigResponse> getProfileSoapAsync(BuildIndicator.AlertDialler.WebDialer.Credential cred, string userid);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:isClusterUserSoap", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WDDeviceInfo))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        bool isClusterUserSoap(string userid);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:isClusterUserSoap", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<bool> isClusterUserSoapAsync(string userid);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:WebdialerSoap")]
    public partial class Credential : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string userIDField;
        
        private string passwordField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string userID {
            get {
                return this.userIDField;
            }
            set {
                this.userIDField = value;
                this.RaisePropertyChanged("userID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:WebdialerSoap")]
    public partial class WDDeviceInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string deviceNameField;
        
        private string[] linesField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string deviceName {
            get {
                return this.deviceNameField;
            }
            set {
                this.deviceNameField = value;
                this.RaisePropertyChanged("deviceName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string[] lines {
            get {
                return this.linesField;
            }
            set {
                this.linesField = value;
                this.RaisePropertyChanged("lines");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:WebdialerSoap")]
    public partial class GetConfigResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descriptionField;
        
        private WDDeviceInfo[] deviceInfoListField;
        
        private int responseCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public WDDeviceInfo[] deviceInfoList {
            get {
                return this.deviceInfoListField;
            }
            set {
                this.deviceInfoListField = value;
                this.RaisePropertyChanged("deviceInfoList");
            }
        }
        
        /// <remarks/>
        public int responseCode {
            get {
                return this.responseCodeField;
            }
            set {
                this.responseCodeField = value;
                this.RaisePropertyChanged("responseCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:WebdialerSoap")]
    public partial class CallResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int responseCodeField;
        
        private string responseDescriptionField;
        
        /// <remarks/>
        public int responseCode {
            get {
                return this.responseCodeField;
            }
            set {
                this.responseCodeField = value;
                this.RaisePropertyChanged("responseCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string responseDescription {
            get {
                return this.responseDescriptionField;
            }
            set {
                this.responseDescriptionField = value;
                this.RaisePropertyChanged("responseDescription");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:WebdialerSoap")]
    public partial class UserProfile : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string userField;
        
        private string deviceNameField;
        
        private string lineNumberField;
        
        private bool supportEMField;
        
        private string localeField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string user {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
                this.RaisePropertyChanged("user");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string deviceName {
            get {
                return this.deviceNameField;
            }
            set {
                this.deviceNameField = value;
                this.RaisePropertyChanged("deviceName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string lineNumber {
            get {
                return this.lineNumberField;
            }
            set {
                this.lineNumberField = value;
                this.RaisePropertyChanged("lineNumber");
            }
        }
        
        /// <remarks/>
        public bool supportEM {
            get {
                return this.supportEMField;
            }
            set {
                this.supportEMField = value;
                this.RaisePropertyChanged("supportEM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string locale {
            get {
                return this.localeField;
            }
            set {
                this.localeField = value;
                this.RaisePropertyChanged("locale");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebdialerSoapServiceChannel : BuildIndicator.AlertDialler.WebDialer.WebdialerSoapService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebdialerSoapServiceClient : System.ServiceModel.ClientBase<BuildIndicator.AlertDialler.WebDialer.WebdialerSoapService>, BuildIndicator.AlertDialler.WebDialer.WebdialerSoapService {
        
        public WebdialerSoapServiceClient() {
        }
        
        public WebdialerSoapServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebdialerSoapServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebdialerSoapServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebdialerSoapServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BuildIndicator.AlertDialler.WebDialer.CallResponse makeCallSoap(BuildIndicator.AlertDialler.WebDialer.Credential cred, string dest, BuildIndicator.AlertDialler.WebDialer.UserProfile prof) {
            return base.Channel.makeCallSoap(cred, dest, prof);
        }
        
        public System.Threading.Tasks.Task<BuildIndicator.AlertDialler.WebDialer.CallResponse> makeCallSoapAsync(BuildIndicator.AlertDialler.WebDialer.Credential cred, string dest, BuildIndicator.AlertDialler.WebDialer.UserProfile prof) {
            return base.Channel.makeCallSoapAsync(cred, dest, prof);
        }
        
        public BuildIndicator.AlertDialler.WebDialer.CallResponse endCallSoap(BuildIndicator.AlertDialler.WebDialer.Credential cred, BuildIndicator.AlertDialler.WebDialer.UserProfile prof) {
            return base.Channel.endCallSoap(cred, prof);
        }
        
        public System.Threading.Tasks.Task<BuildIndicator.AlertDialler.WebDialer.CallResponse> endCallSoapAsync(BuildIndicator.AlertDialler.WebDialer.Credential cred, BuildIndicator.AlertDialler.WebDialer.UserProfile prof) {
            return base.Channel.endCallSoapAsync(cred, prof);
        }
        
        public BuildIndicator.AlertDialler.WebDialer.GetConfigResponse getProfileSoap(BuildIndicator.AlertDialler.WebDialer.Credential cred, string userid) {
            return base.Channel.getProfileSoap(cred, userid);
        }
        
        public System.Threading.Tasks.Task<BuildIndicator.AlertDialler.WebDialer.GetConfigResponse> getProfileSoapAsync(BuildIndicator.AlertDialler.WebDialer.Credential cred, string userid) {
            return base.Channel.getProfileSoapAsync(cred, userid);
        }
        
        public bool isClusterUserSoap(string userid) {
            return base.Channel.isClusterUserSoap(userid);
        }
        
        public System.Threading.Tasks.Task<bool> isClusterUserSoapAsync(string userid) {
            return base.Channel.isClusterUserSoapAsync(userid);
        }
    }
}
